## -------------
## Name: Link1kmMODdat_Grid.r
## Program version: R 3.1.0
## Dependencies: plyr, stringr
## Function file: Functions_LinkMODdat_Grid.r
## Author: J.H. Belle
## Purpose: Calculate AOD averages for each CMAQ grid cell, using the lists of pixel UID's generated by the gridding process
## -------------
## Load libraries and functions
library(plyr)
library(stringr)
source("T://eohprojs/CDC_climatechange/Jess/Dissertation/Aim1Repo/Functions_LinkMODdat_Grid.r")
# ----
# Define relevant parameters
# ----
## These values are passed in through the command line
#args = commandArgs(trailingOnly=T)
#Endday = as.numeric(args[2])
#Startday = as.numeric(args[1])
Endday=366
Startday=1
## Year
Year = 2012
TAflag="T"
ListBroken = c()
## Location of MODIS files - extracted from hdf section-specific csvs using GriddingExtractMODIS10km.m
MODpaths = c("/gc_runs/MYD03_Calif/Extractions_Terra_STop/", "/gc_runs/MYD03_Calif/Extractions_Terra_STop2/", "/gc_runs/MYD03_Calif/Extractions_Terra_SBot/", "/gc_runs/MYD03_Calif/Extractions_Terra_SBot2/")
## Location of grid
GridPaths = c("/gc_runs/MYD03_Calif/Gridded_Terra_STop/", "/gc_runs/MYD03_Calif/Gridded_Terra_STop2/", "/gc_runs/MYD03_Calif/Gridded_Terra_SBot/", "/gc_runs/MYD03_Calif/Gridded_Terra_SBot2/")
## Location of data files - data from cloud product - linked by index/mask value
DataPath = ""
## Location of output files
OutPath = ""
## Scale value for AOD - from MODIS hdf files
Emisscale = 0.009999999776482582
# --------
# Load in csv files for each section - Gridding results and MODIS data, and calculate desired values
# --------
for (Day in Startday:Endday){
  for (s in 1:length(GridPaths)){
    #print(section)
    ## Read in MODIS data, and create necessary variables - timestamp, UIDs and scaled AOD values
    Mod <- try(read.csv(sprintf("%sExtr_%i_%03d_S1.csv", MODpaths[s], Year, Day)))
    if (is.data.frame(Mod)){
      Mod$timestamp <- paste(sprintf("%02d:%02d", Mod$hr, Mod$min))
      Mod$UID <- sprintf("G%i_%03d_%s_P%f_%f", Year, Day, Mod$timestamp, Mod$Lat, Mod$Long)
      Mod$UID <- gsub("[[:punct:]]", "", Mod$UID)
      Cloud <- read.csv(sprintf("%sExtr_%i_%03d_S1_%s.csv", DataPath, Year, Day, TAflag))
      ## If the gridding output file exists (a few days/sections had no data and files for those days weren't created during gridding), read it in
      Grid <- try(read.csv(sprintf("%sOutp_%i_%03d_S%i_%s.csv", GridPaths[s], Year, Day, section, TAflag), stringsAsFactors=FALSE))
      if (is.data.frame(Grid)) {
        ## Summarize MODIS data in each cell of the CMAQ grid - function CalcVals defined in function file
        CombOut <- ddply(Grid, .(US.id), CalcVals, MODdat=Mod, Clouddat=Cloud, scale=Emisscale)
        rm(Mod, Grid)
        gc()
        ## Join output to that from previous section, if it exists
        if (exists("OutpDay")){
          OutpDay <- rbind.data.frame(OutpDay, CombOut)
        } else {
          OutpDay <- CombOut
        }
        rm(CombOut)
        gc()
      }
    }
  }
  ## Aggregate OutpDay


  ## Write output csv
  write.csv(OutpDay, sprintf("%sDailyGridAOD_%i_%03d.csv", OutPath, Year, Day))
  rm(OutpDay)
}
